### ISSUE TITLE
Update the `approx` dependency

### ISSUE THREAD

**Issue by yoanlcq** [yoanlcq/vek#13]
Some traits have changed from 0.1.0 to current 0.3.0, meaning `vek` is not compatible with the latest `approx` (which is annoying. Hand-rolling comparisons is possible, but no fun.)

**Comment by Imberflur** [comment]
#41 did this @yoanlcq

**Comment by yoanlcq** [comment]
Yup, thanks for the reminder! This is now fixed in the current master branch and will be part of 0.10.0 which I'll publish very soon.
I'm closing this even though this isn't really "fixed" until I publish the new version.
