### ISSUE TITLE
Implement a `into_square_array() -> [[T; 4]; 4]` method for `Mat4`

### ISSUE THREAD

**Issue by zesterer** [yoanlcq/vek#17]
This would be a really useful feature for interoperability with `gfx`. Currently, I'm having to use a dirty utility function to convert a `Mat4` into a `[[T; 4]; 4]`.

**Comment by yoanlcq** [comment]
Why not... What concerns me most is the name; there's `into_col_array` and `into_row_array` which make row-major vs. column-major explicit, in such a way a compile-time error would be generated if we were to switch layouts. Granted, this almost never happens, so the argument would rather be "let's be consistent with what is there already"...

The first thing that comes to my mind is `into_row_array_array` and `into_col_array_array`, or `into_array_of_rows`/`into_array_of_cols`. I would be fine with these last two; what do you think?

**Comment by zesterer** [comment]
I feel that `into_array_of_rows`/`into_array_of_cols` is the more natural option. `into_row_array_array` sounds very unintuitive, and unnecessarily wordy, even if it's technically a correct description.

With regards to #18, I'd be strongly in support of such a thing. `mint` compliance would make it easier for people to use `vek` within other projects, and also make it easier to use dependencies that don't use `vek` in `vek`-oriented projects.

**Comment by yoanlcq** [comment]
This is now fixed with the latest release, 0.9.6. I've settled with adding an extra "s" to the existing names for flat array conversions. So now there's `into_row_array` and `into_row_arrays`. This way I think we preserve consistency without sacrificing clarity.
