### ISSUE TITLE
Multiple `cannot borrow as immutable because it's borrowed as mutable` warnings

### ISSUE THREAD

**Issue by CryZe** [yoanlcq/vek#25]
There's a lot of warnings that variables are borrowed immutably while also being borrowed mutably in the currently released version of vek (0.9.7)

```rust
warning[E0502]: cannot borrow `rows` as immutable because it is also borrowed as mutable
    --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\vek-0.9.7\src\mat.rs:1897:31
     |
1897 |                 rows[3][0] += rows[0].dot(t);
     |                 --------------^^^^----------
     |                 |             |
     |                 |             immutable borrow occurs here
     |                 mutable borrow occurs here
     |                 mutable borrow later used here
...
3952 |     mat_declare_modules!{}
     |     ---------------------- in this macro invocation
     |
     = warning: this error has been downgraded to a warning for backwards compatibility with previous releases
     = warning: this represents potential undefined behavior in your code and this warning will become a hard error in the future
```

**Comment by yoanlcq** [comment]
Whoa! This is new. Which `rustc` version are you using?

The example surprises me, because T is `Copy`, so once the right-hand side is evaluated, `rows[0]` isn't supposed to remain borrowed immutably. It would have been nice if the warning linked to an issue, so I could see some discussion around it.

**Comment by CryZe** [comment]
I think the issue is that they accidentally stabilized two phase borrows with Rust 2018 and are now backing away from it again, since it's unclear if they can define a memory model for it that supports them. The problem here is that rows[3][0] gets borrowed mutably, but considering arrays are kind of stupid in Rust, the whole rows array is therefore mutably borrowed until the += is over. So you can't access the rows[0], because it already is mutably borrowed. So in a way the problem is that rows[3][0] gets evaluated before the right hand side here.
