### ISSUE TITLE
Tab and Space Craziness in src/ops.rs

### ISSUE THREAD

**Issue by CryZe** [yoanlcq/vek#26]
There seem to be random tabs and spaces all over the place in at least src/ops.rs which rustdoc apparently can't deal with: 
```
warning: could not parse code block as Rust code
   --> C:\Users\Christopher Serr\.cargo\registry\src\github.com-1ecc6299db9ec823\vek-0.9.7\src\ops.rs:306:6
    |
306 |       ///    ```
    |  ____________^
307 | |     /// use vek::ops::Lerp;
    | |_
    |
    = note: error from rustc: unknown start of token: `
```

**Comment by yoanlcq** [comment]
Yes, that's my bad. I said in #16 I would fix it, but then I forgot. However I never had such problems with rustdoc; things sure have changed since last time I compiled `vek`. :) 

I'll see and try to fix it for real this time.

**Comment by yoanlcq** [comment]
Hmm... `cargo doc` with the latest nightly (1.36) doesn't report any errors on my side. I'll still get rid of tabs though.

**Comment by yoanlcq** [comment]
Well I think it's fixed now, since I don't get any errors. Feel free to re-open otherwise.
