### ISSUE TITLE
Implement std::iter::Sum for types with Add trait implementation

### ISSUE THREAD

**Issue by sunjay** [yoanlcq/vek#31]
I think it would be a good idea to implement the [`std::iter::Sum`](https://doc.rust-lang.org/stable/std/iter/trait.Sum.html) trait for all `vek` types that can be added together. Then we can use `.sum()` on an iterator of those types to add them up.

**Comment by yoanlcq** [comment]
Indeed! This is now implemented [since this commit](https://github.com/yoanlcq/vek/commit/f5d89bdf84d97e099aef557ce1b5f60a104019fe).

**Comment by sunjay** [comment]
Thank you! Do you think it makes sense for other types that implement the Add trait as well?

**Comment by yoanlcq** [comment]
I'm not sure; how often is it needed to sum matrices/quaternions/curves/shapes together? In my experience, not much; the same would apply for `Product`. If someone really needs it, then they may request it, as usual, though it looks unlikely to me :)

I'll close this, but feel free to add to the discussion; also let me know if you'd like a new version immediately (by default I prefer to wait until enough features have made it)!

**Comment by sunjay** [comment]
Makes sense. Thanks! I also only need it for vectors right now. I'd be happy if you released it, but I also already worked around it so it's totally not urgent. Up to you. :)

Appreciate you being so responsive! :D
