### ISSUE TITLE
Add a .xy() method to get lower dimension components of a vector

### ISSUE THREAD

**Issue by zesterer** [yoanlcq/vek#36]
While this is already possible with `Vec2::from(my_vec3)`, the required type annotations makes it wordy enough to be annoying to do for such a common operation. A `.xy()` method would make this significantly more ergonomic.

**Comment by yoanlcq** [comment]
Fixed by [bc185ba](https://github.com/yoanlcq/vek/commit/bc185ba361ae6525f9fd002c833df4563b9aa399)
