### ISSUE TITLE
Upgrade `num_traits` dependency

### ISSUE THREAD

**Issue by Imberflur** [yoanlcq/vek#46]
Currently the version used is `~0.1.40` while the latest `num_traits` is `0.2.11`

**Comment by Imberflur** [comment]
I just saw that #41 does this

**Comment by yoanlcq** [comment]
Thanks for reporting this! #41 is now merged.
I'm currently looking into updating all dependencies and compiling on `no_std`.

**Comment by yoanlcq** [comment]
This will be fixed in the next version today.
