### ISSUE TITLE
Display impl should respect formatting parameters just like Debug

### ISSUE THREAD

**Issue by martin-t** [yoanlcq/vek#57]
Example: Currently formatting with `{:.2?}` correctly shows only 2 decimal places but using `{:.2}` prints all the digits.

I took a brief look at the code and I think it's only a matter of slightly modifying the macro:
- take only e.g `"rgba"` instead of `"rgba({}, {}, {}, {})"`
- iterate through the vector's elements and pass them the `Formatter` when printing them

If you agree, i should be able to make a PR.

**Comment by yoanlcq** [comment]
Hi, 

Yes, feel free to open a PR! What you describe seems to be the correct way to fix the issue.
