### ISSUE TITLE
Casting can no longer produce undefined behavior (UB)

### ISSUE THREAD

**Issue by martin-t** [yoanlcq/vek#59]
It looks like the 2 issues linked [here](https://docs.rs/num-traits/0.2.12/num_traits/cast/trait.AsPrimitive.html#safety) and in some other places have been resolved and [the reference](https://doc.rust-lang.org/reference/expressions/operator-expr.html#semantics) has been updated too.

Should i update the docs?

**Comment by yoanlcq** [comment]
Updating the docs is a good idea. One thing to consider is that some users may not be using the latest 1.45.0 of Rust, so what I think I'll do right now is change the docs to say "hey, if you're using a version Rust before 1.45.0, then you may encounter UB as described: [insert current doc about UB here]".

Then I guess one day Rust 1.45.0 would be widespread enough that we could completely remove to parts of the doc about UB. I am unsure of when that day will come and how to measure it, but I guess that'll be fine.

**Comment by yoanlcq** [comment]
That should be fine, let me know if you have any thoughts about this.

**Comment by martin-t** [comment]
I noticed the text here originally comes from the num-traits crate and opened a [PR there](https://github.com/rust-num/num-traits/pull/184). In the process, i noticed the second case (float to float conversion) probably never was UB and the second example might be removed. Might wanna keep an eye on that PR to keep the docs in sync.
