### ISSUE TITLE
Add `From<(Vec2<T>, T)>` for `Vec3<T>`?

### ISSUE THREAD

**Issue by Imberflur** [yoanlcq/vek#71]
Right now this either has to be done by:
```rust
Vec3::new(vec2.x, vec2.y, z)
```
or
```rust
Vec3::from(vec2) + Vec3::unit_z() * z
```
where it could just be
```rust
Vec3::from((vec2, z))
```
And this would be really convenient in creating APIs that take `Into<Vec3<T>>` since then just `(vec2, z)` could be passed in instead of having to convert it.

**Comment by yoanlcq** [comment]
Interesting, PR #70 is a bit related. Although, I understand how what is being asked here is slightly different, and I agree that it would be elegant.

I'll look into this today.

**Comment by yoanlcq** [comment]
I closed this in a commit, but I still need to wait for CI to greenlight this. When it's OK, I'll publish a new version with this feature.

**Comment by yoanlcq** [comment]
Version 0.14.1 has been published just now with this feature. Thanks!
