### ISSUE TITLE
Consider re-exporting crates with traits that vek depend on

### ISSUE THREAD

**Issue by NiklasJonsson** [yoanlcq/vek#75]
I tried to use [Mat4::abs_diff_eq](https://docs.rs/vek/0.15.0/vek/mat/repr_c/column_major/mat4/struct.Mat4.html#impl-AbsDiffEq%3CMat4%3CT%3E%3E) but it seems to be implemented using a trait from another crate (`approx`). As I understand it, in order to  use this I have to add `approx` to my own Cargo.toml and make sure the versions match. In case of version mismatch  (IIRC if I specify a version `vek` is not compatible with) it won't compile. If I have another dependency which uses `approx` similarly, I'm not sure I can resolve it if `vek` and my other dependency don't agree on compatible versions?

Anyhow, I'd prefer if `vek` re-exported crates (or maybe just the traits) so that I can get the right `approx` version with something like:
`use vek::approx::AbsDiffEq`
There is some related discussion in the api-guidelines repo [here](https://github.com/rust-lang/api-guidelines/discussions/176)

**Comment by yoanlcq** [comment]
This is very useful information! I've published a new version `0.15.1` with what I think is the appropriate fix. Please let me know if that works for you.

**Comment by NiklasJonsson** [comment]
It works great, thank you for the quick response!

**Comment by yoanlcq** [comment]
Anytime!
